[global]
#dataFrameSerialization = "legacy"

[logger]
level = "info"

[browser]
gatherUsageStats = false

[server]
port = 8801
headless = true
baseUrlPath = "littlefield"

[theme]
# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace)
# Default: "sans serif"
font = "sans serif"